### ISSUE TITLE
Add the ability to hide an option

### ISSUE THREAD

**Issue by cazador481** [celogeek/MooX-Options#30]
Can you please add an ability to hide an option from the help message?
Looks like this can be accomplished with Getopt::Long::Descriptive if you use the hidden attribute.

I can see 2 ways to do this,
one create a hidden attribute for the option,
another one would be to not show any private options.  i.e any options that start with an _

Thanks,
Eddie

**Comment by celogeek** [comment]
I haven't setup the "hidden" attribute. But I can add it.

In the mean time, if you setup "doc" => "hidden", it will pass this to getopt long descriptive, and then will hide the attribute from doc.

```
#!perl
use Moo;
use MooX::Options;


option 'testh' => (is => 'ro', hidden => 1, doc => 'hidden');
option 'test' => (is => 'ro');


print main->new_with_options->testh,"\n";
```

Try perl this_script.pl -h
and this_script.pl --testh
