### ISSUE TITLE
Allow dashes in arg names

### ISSUE THREAD

**Issue by oalders** [celogeek/MooX-Options#31]
I've kind of gotten used to https://metacpan.org/pod/MooseX::Getopt::Dashes  Would it be possible to optionally allow dashes in argument names?   I could provide a patch if you're open to this.  Or is there a different module I should be looking at?

**Comment by celogeek** [comment]
Dash is already supported. When you declare :

```
option 'my_option_with_dash' => ( ...)
```

You can use any combinaison of dash :

my_option_with-dash
my_option-with-dash
my-option-with-dash

**Comment by oalders** [comment]
Perfect. Thanks for clearing that up.  I had searched the docs for "dash" and wasn't seeing anything. :)

**Comment by celogeek** [comment]
Well, you are right, I need to improve my doc.

Le Mon Jan 26 2015 at 19:56:08, Olaf Alders <notifications@github.com> a
écrit :
