### ISSUE TITLE
Use the value of init_arg to specify the command line name of the option.

### ISSUE THREAD

**Issue by djerius** [celogeek/MooX-Options#33]
Somtimes an option's name on the command line must differ from the name of its attribute.   If I were doing this for a normal class, I'd use the `init_arg` option to `has` to specify the alternate constructor name.

It would be great if `MooX::Options` used the value of `init_arg` as the name of the command line option if it were specified.

BTW, specifying `init_arg` currently breaks the option, as `MooX::Options` uses the
attribute  name, but that is out of sync with the name that the constructor expects so the option is ignored.

Thanks,
Diab

**Comment by celogeek** [comment]
Can you provide an example please ?

**Comment by celogeek** [comment]
With Moose you can use the "accessor" option :

option 'myoptions' => (format => 's', accessor => '_myaccessor');

So you have --myoptions and your accessor will be _myaccessor.

It is what you want I think.
