### ISSUE TITLE
MooX::Options doesn't support the increment getopt 

### ISSUE THREAD

**Issue by cazador481** [celogeek/MooX-Options#39]
Please add an inc/increment option, it is currently missing.

For completeness description of what increment does:
+    The option does not take an argument and will be incremented by 1 every time it appears on the command line. E.g. "more+", when used with --more --more --more, will increment the value three times, resulting in a value of 3 (provided it was 0 or undefined at first).

    The + specifier is ignored if the option destination is not a scalar.

**Comment by frioux** [comment]
I don't think this is accurate, it looks supported to me: https://metacpan.org/source/CELOGEEK/MooX-Options-4.018/lib/MooX/Options/Role.pm#L32

**Comment by celogeek** [comment]
Yes. Increment is already implemented with the repeatable option.
