### ISSUE TITLE
Provide an option to disable required options in parent commands

### ISSUE THREAD

**Issue by cspann** [celogeek/MooX-Options#42]
We use MooX::Options together with MooX::Cmd to build a CLI Application with multiple layers of sub commands. Unfortunately it is not possible to declare options required in intermediate command levels when subcommands do not need these options. 

Even the help command fails if one of the higher commands has a required attribute which is not provided additionally with the --help.

It would be nice to have a mean to define the required attribute in a way that it only is parsed when the option is part of the most specific command or if subcommands can disable required options from parent commands. 

Example: 

cmd has an option 'attr'

```
cmd subcmd --help
attr is missing 
USAGE: cmd subcmd [-h] [long options...]
```

**Comment by rehsack** [comment]
@cspann - this is unfortunately impossible due the architecture of Moo & MooX::Cmd.

When you have a parent command class which has a required attribute, than it has a required attribute. The class will be instantiated and fails during building the instance due the missing required attribute.

No further attempts to go deeper are made ...

Please have a look at http://www.netbsd.org/~sno/talks/nrpm/Moo-at-App-Math-Trainer.pdf to get a deeper introduction how the instantiation works.
