### ISSUE TITLE
Help does not display short/aliases

### ISSUE THREAD

**Issue by yshtil** [celogeek/MooX-Options#43]
I have the following script:

use strict;

use MyClass;

my $s = MyClass->new_with_options;

And MyClass.pm:

use strict;

package MyClass;

use Moo;
use MooX::Options;
# option 'account_id' => (is => 'ro', format => 'i', short => 'a|id', doc => 'doc');

option 'account_id' => (is => 'ro', format => 'i', short => 'a', doc => 'doc');

1;

The help message in this case is what I expected:

perl p.pl -h
USAGE: p.pl [-ah] [long options...]

```
-a --account_id: Int
    doc
```

...

However if I activate the second option line in the script instead of the first:

option 'account_id' => (is => 'ro', format => 'i', short => 'a|id', doc => 'doc');
# option 'account_id' => (is => 'ro', format => 'i', short => 'a', doc => 'doc');

The help message has no info about the aliases at all:

perl p.pl -h
USAGE: p.pl [-ah] [long options...]

```
--account_id: Int
    doc
```

I expected something like:

 -a --is  --account_id: Int
        doc

**Comment by celogeek** [comment]
I think the short option handle only one alias.

can you provide a patch for it ?

**Comment by yshtil** [comment]
I am pretty busy at work at this time, Maybe in a month or so. 

----- Original Message -----

**Comment by rehsack** [comment]
Has your business settled a bit? Or are you so much busy that this has outlived?
