### ISSUE TITLE
--help produces too many empty lines

### ISSUE THREAD

**Issue by van-de-bugger** [celogeek/MooX-Options#46]
Consider an example:

    #!/usr/bin/perl
    {
        package MyOpt;
        use Moo;
        use MooX::Options;
        option 'one' => (
            is  => 'ro',
        );
        option 'two' => (
            is  => 'ro',
        );
    }
    my $a = MyOpt->new_with_options();

And its output:

    $ perl ./moo-options.pl --help
    USAGE: moo-options.pl [-h] [long options...]

        --one:
            no doc for one

        
        --two:
            no doc for two

        
                                                                                
        
        
        --usage:
            show a short help message

        
        -h:
            show a compact help message

        
        --help:
            show a long help message

        
        --man:
            show the manual

        

Every option is separated from others with two empty lines. Option groups are separated by 5(!) empty lines. It seems one empty line between options and two between groups is enough.

**Comment by celogeek** [comment]
yes, sorry, I need to fix this

**Comment by celogeek** [comment]
fixed in 4.022
