### ISSUE TITLE
[Feature request] Support for --version option.

### ISSUE THREAD

**Issue by van-de-bugger** [celogeek/MooX-Options#47]
`--version` option can be easily implemented in client code. However, it would be nice to have support for `--version` option directly in `MooX::Options` because:
1. `--version` option is required in almost every script. Even if it is not required, it does not hurt.
2. If `--version` option is implemented by the client code, it is shown in the group with other "functional" options, while it should be groped with other "non-functional" options `-h`, `--usage`, `--help`, and `--man`, because these options (include `--version`) show some info and exit without doing any other actions.

**Comment by celogeek** [comment]
Oh, I see, nice, I note this.

**Comment by cazador481** [comment]
FYI: Getopt::Long::Descriptive has it already built in.  I do request that the --version line be hidden in the --help, as it is starting to get unwieldy.

**Comment by rehsack** [comment]
@van-de-bugger and @celogeek - I do not see how this can be reasonable implemented in `MooX::Options` automatically. A client driven `--version` might be sane under some circumstances and I'm happy to act as sounding board to figure out the boundary conditions for `MooX::Options` support.

If one doesn't know - lot's of company in-house development isn't versioned in any Perl module, it is done by doing release tags in git-repository based on the head commit and the timestamp. This is the released version of a software.
