### ISSUE TITLE
utf8 characters in doc are not displayed correctly when binmode STDERR, ':utf8' is active

### ISSUE THREAD

**Issue by cspann** [celogeek/MooX-Options#48]
I tried to track this down but did not manage to find the reason yet. Maybe we can work this out together:

When I use german umlauts in the doc section of an option and utf-8 binmode is enabled in stderr or globally via `PERL_UNICODE=AS`, `cmd --help` produces a broken output which is due to a [unicode character interpreted as ASCII](http://www.i18nqa.com/debug/utf8-debug.html) I guess.

Example: `Berücksichtige nur Jobs ...` gets  `BerÃ¼cksichtige nur Jobs...`

This problem is already present if I do `print $attributes{'doc'}` in Options.pm line 195 or so.

The source file is encoded in utf8 and has use utf8 enabled.

Regards,
Christian

**Comment by celogeek** [comment]
Can you create a test unit that show the problem please.

**Comment by cspann** [comment]
I created a pull request (#51) with a modified test case of yours.

**Comment by cspann** [comment]
@rehsack why did you close this issue?

**Comment by rehsack** [comment]
Because there is a pull-request for the issue. No need for 2 open trackers.

**Comment by cspann** [comment]
Err - no? The pull request was closed long before the issue which is still not fixed and did only introduce tests which check if the error is still present. What am I missing...?

**Comment by rehsack** [comment]
As written, I didn't realize that the PR was closed - sorry for that.
Anyway - an issue which doesn't disturb anyone neither has any outcome for ages isn't worth to be tracked.

I'm fine with working it out together - but, if wanted - open a new PR which clearly demonstrates the issue, bugging on Travis and - if not obvious - ask expert people to help us.

But what is needed first is a open visible, reasonable test demonstrating the issue.

**Comment by cspann** [comment]
Oh - sorry I completely missed the second sentence in your previous post. 

If I find some time I will try to clarify the issue - even though celogeek already acknowledged the issue as commented in the Pull Request. 
The argument that nobody is disturbed has some points on one side but still german users as we both are are definitely somehow disturbed as the output of the options doc is broken if utf8 characters are present. This does not kill people but it degrades usability in my opinion.

**Comment by rehsack** [comment]
My point wasn't regarding the existence of the issue - it's more "noone (else) seems to care". This can have multiple reasons but all lead to the same: open and orphaned issue.

If you need help figuring out a test, I suggest you ask some people who use utf8 on regular basis, like H.Merijn Brand or Steffen Winkler.
