### ISSUE TITLE
Is perl 5.10.0 really required?

### ISSUE THREAD

**Issue by karenetheridge** [celogeek/MooX-Options#53]
`use feature 'state'` appears in a .pm, but then `state` is never used. And it looks like `say` is only used in a few tests, which could easily be removed.  Is there another reason for requiring 5.10?

**Comment by celogeek** [comment]
yes, I see, I fix it.

**Comment by celogeek** [comment]
the dzil package required 5.10 to create the package. But the deps can be removed.
I check if I can install the package properly

**Comment by celogeek** [comment]
that is not really nice, one test failed on 5.8.9. I try to figure out.

**Comment by celogeek** [comment]
fixed in devel, I will try hard to work on moox options to do a release this month
