### ISSUE TITLE
[question] How do I use - instead of -- in my arguments?

### ISSUE THREAD

**Issue by cazador481** [celogeek/MooX-Options#54]
I would like to use a single - instead of -- to pass my arguments, how would I go about doing that?

I have tried doing flavour=>(no_bundling) ,and that gets me 50% of the way there as
-cfg=1 works, but -cfg 1 doesn't.

**Comment by celogeek** [comment]
You can't, they is a preprocessing done by MooX::Options that all option as long, or short (with 1 char).

The module GetOpt::Long evolve a lot, and MooX::Options doesn't support all their options.
