### ISSUE TITLE
negativable options that default to one should display --no-option in the help

### ISSUE THREAD

**Issue by robrwo** [celogeek/MooX-Options#60]
If an option is "negativable" and the default is 1, then it should show the option in help as "--no-foo" instead of "--foo".

A caveat: I work around this by putting "(use --no-foo to disable)". So if "--no-foo" appears in the doc, then just show "--foo".

**Comment by celogeek** [comment]
The default value is hard to guess. We don't execute it until we really need it. So a good explanation in the doc is preferable.

To know that a --foo is 1 by default, and can de disabled is better than guessing it.
