### ISSUE TITLE
Short version and alias with negativable or negatable sets wrong value

### ISSUE THREAD

**Issue by 1shad** [celogeek/MooX-Options#64]
Hello,

When an option is set up like this:

`option fullscreen => (   
    is => 'ro',
    short => 'f|fs',
    negatable => 1,
);
`

fullscreen is set to 1 when --no-fs command line parameter is used.

with:

`short => 'fs',`

it is set to 0 as expected with --no-fs.

**Comment by rehsack** [comment]
The short flag is intended (and documented) as `short => 'fs'` - the is (even when functionality isn't prevented) no support for specifying multiple short aliases.

If you require this feature, please submit a reasonable patch providing it together with tests for the new feature.
