### ISSUE TITLE
new_with_options and short options

### ISSUE THREAD

**Issue by jddurand** [celogeek/MooX-Options#65]
Upgrading to version ``4.100`` I got a failure with short options, c.f. https://rt.cpan.org/Ticket/Display.html?id=122395 .
Not sure this come from my code, though: I isolated a potential issue with ``new_with_options``, i.e.:

``perl -MMoo -MMooX::Options -e 'option interactive => (short => "i"); option include => (short => "Z"); __PACKAGE__->new_with_options();'
``

raises:

``There is already an abbreviation 'i' - can't use it to shorten 'interactive' at -e line 1.``

Can you please tell me if I have to adapt my code and how ? Thanks!

**Comment by rehsack** [comment]
1) Please use the specified ticket queue
2) This discovers a sleeping issue in all versions before.

I think, MooX::Options needs a 2-phase abbrevation generator - first the explicit specified ones and then fill up with the automatic computed ones. The clashing computed shall be removed.

I currently work on a list_compare in List::MoreUtils - it could be a reasonable tool to solve this issue.

**Comment by jddurand** [comment]
Specified ticket queue? MooX::Options "View/Report Bugs" link on CPAN explicitly redirects to github, not RT, if this is what you mean. I will nevertheless explicit open a ticket then and try to link my RT to it.

Thanks for your help.

**Comment by jddurand** [comment]
https://rt.cpan.org/Ticket/Display.html?id=122410

**Comment by rehsack** [comment]
Yes, I meant https://github.com/celogeek/MooX-Options/blob/master/Makefile.PL#L43 - I don't know which "CPAN" redirects to github. MetaCPAN.org and search.cpan.org link both to http://rt.cpan.org/Public/Dist/Display.html?Name=MooX-Options. @ether expresses an assumption in https://rt.cpan.org/Ticket/Display.html?id=122348 - but to prove @celogeek needs to close this ticket queue. I'll figure that out the other place :)

**Comment by jddurand** [comment]
Yes, you're right - MooX-Options-4.018 redirects to github, but MooX-Options-4.100 redirects to CPAN - sorry about that, this probably confused me... / regards.

**Comment by rehsack** [comment]
Would you please be so kind and test the fix in https://github.com/rehsack/MooX-Options ?

**Comment by rehsack** [comment]
Uploaded 4.102 should deploy the fix

**Comment by jddurand** [comment]
Many thanks for the fix, and apologizes for not answering before, I was away.
Will test that with a config on which I remember pretty well this was reproducible -;

**Comment by jddurand** [comment]
Fix is ok as far as I can see - many thanks
