### ISSUE TITLE
Error while prompting for user input

### ISSUE THREAD

**Issue by neybar** [celogeek/MooX-Options#66]
I'm using MooX::Options and I want to prompt for user input if something isn't passed in.  When I prompt for input I'm getting this error:

```prompt(): Can't open *ARGV: No such file or directory at ./iam-role-setup.pl line 56.```

I'm using IO::Prompter for input.  I tried a few other options/modules and they all have similar issues.

Here is an example script (test.pl):
```
#! /usr/bin/env perl

use Moo;
use MooX::Options;
use IO::Prompter;
use feature 'say';

option "verbose" => (
    is => 'ro',
    short => 'v',
    doc => 'Turn on verbose logging',
    default => 0,
);

option "username" => (
    is => 'lazy',
    format => 's',
    short => 'u',
    doc => "Your username",
);

sub _build_username {
    my ($self) = @_;
    prompt -v, "Enter your username";
}

sub run {
    my ($self) = @_;
    say $self->verbose;
    say $self->username;
}
main->new_with_options->run;
```

Try calling ```test.pl -v```

**Comment by rehsack** [comment]
When I run this - without IO::Prompter, since this isn't MooX:Options topic

    {
	package Stuff;

	use Moo;
	use MooX::Options;
	# use IO::Prompter;
	use feature 'say';

	option "verbose" => (
	    is => 'ro',
	    short => 'v',
	    doc => 'Turn on verbose logging',
	    default => 0,
	);

	option "username" => (
	    is => 'lazy',
	    format => 's',
	    short => 'u',
	    doc => "Your username",
	);

	sub _build_username {
	    my ($self) = @_;
	    # prompt -v, "Enter your username";
	    return "me";
	}

	sub run {
	    my ($self) = @_;
	    say $self->verbose;
	    say $self->username;
	}
    }

    Stuff->new_with_options->run;`

I get

    0
    me

BTW: This is similar to abusing the main-namespace, but however. Did you try to use the prompt() from ExtUtils::MakeMaker? I added that prompt to your example and receive

    0
    Enter your username  foo
    foo

I have no idea what in `./iam-role-setup.pl line 56.` happens neither what prompt expects you to do.
